version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: my-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nextjs:
    build:
      context: .
    container_name: my-nextjs
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://myuser:mypassword@postgres:5432/mydatabase"

volumes:
  postgres-data: